apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
        - name: web-server
          image: yuva19102003/frontend:724d4c90e3d4e8cd20fdf1a6ee8bf042777d8da6
          ports:
            - containerPort: 3000
          env:
            - name: API_KEY
              value: 'http://golangapi-service:8080'
         
