apiVersion: v1
kind: Secret
metadata:
  name: secretkv
  namespace: app
type: Opaque
data:
  USER: cm9vdA==    # Base64 encoded value of 'username'
  PASS: cm9vdA==    # Base64 encoded value of 'password'
  DB: YW5pbWVfZGI=
