apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: yuva19102003/database:96b87d23d9f63dbfbd989a69617e6ffc999336ec
          ports:
            - containerPort: 3306

