---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: project-microservices-quote-generator
    notifications.argoproj.io/subscribe.on-sync-failed.slack: project-microservices-quote-generator
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: project-microservices-quote-generator
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/yuva19102003/DevSecOps-project.git
    targetRevision: manifest
    path: database
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
